-- AlterTable
ALTER TABLE "MockTestAttempt" ADD COLUMN     "answers" JSONB,
ADD COLUMN     "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'IN_PROGRESS',
ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "percentage" SET DEFAULT 0,
ALTER COLUMN "completedAt" DROP NOT NULL,
ALTER COLUMN "completedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "MockTestQuestion" ADD COLUMN     "imageUrl" TEXT,
ADD COLUMN     "negativeMarks" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "optionsAs" TEXT[],
ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "section" TEXT NOT NULL DEFAULT 'General',
ADD COLUMN     "textAs" TEXT,
ALTER COLUMN "marks" SET DEFAULT 4;
